// src/components/projects/projectsDisplay/projectsDisplay.tsx
import { useState, useEffect } from 'preact/hooks';

import { Project } from '../../../types/Project'
import ProjectsFilter from '../projectsFilter/projectsFilter';
import ProjectView from '../projectView/projectView';

import './projectsDisplay.scss';

const ProjectsDisplay = ({ projectsArr }:{ projectsArr: Project[] }) => {
  const [ filters, setFilters ] = useState< string[] >([]);
  const [ filteredProjects, setFilteredProjects ] = useState< Project[] >(projectsArr);

  useEffect( () => {
    if ( filters.length === 0 ) {
      setFilteredProjects(projectsArr)
      return;
    };
    const filteredProjects = projectsArr.filter( project =>  {
      let isIncluded = true;
      for ( const filter of filters ) {
        if( !project.tags.includes(filter) ) {
          isIncluded = false;
          break;
        }
      }
      return isIncluded;
    });
    setFilteredProjects(filteredProjects);
  }, [ filters, projectsArr ]);

  return (
    <div className='projects-display'>
      <div className='filters-wrapper'>
        <ProjectsFilter filters={ filters } setFilters={ setFilters }/>
      </div>
      <div className='projects-wrapper'>
        {
          filteredProjects.map(( project ) => <ProjectView key={ project.slug } projectData={ project } />)
        }
        {
          filteredProjects.length === 0 ? <p style={{ padding: '2rem 0', textAlign: 'center' }}>Sorry, i have no project with the specified filters!</p> : null
        }
      </div>
    </div>
  )
}

export default ProjectsDisplay

// src/components/projects/projectsDisplay/projectsDisplay.svelte
<script>
  import ProjectsFilter from '../projectsFilter/projectsFilter.svelte';
  import ProjectView from '../projectView/projectView.svelte';
  
  import './projectsDisplay.scss';

  export let projectsArr;
  const filters = [];
  const filteredProjects = [ ...projectsArr ];

  const setFilters = ( filterArr ) => {
    const filters = [ ...filterArr ];

    if ( filters.length === 0 ) {
      setFilteredProjects(projectsArr)
      return;
    };
    const filteredProjects = projectsArr.filter( project =>  {
      let isIncluded = true;
      for ( const filter of filters ) {
        if( !project.tags.includes(filter) ) {
          isIncluded = false;
          break;
        }
      }
      return isIncluded;
    });
  } 
</script>

<div class='projects-display'>
  <div class='filters-wrapper'>
    <ProjectsFilter filters={ filters } setFilters={ setFilters }/>
  </div>
  <div class='projects-wrapper'>
    { #each filteredProjects as project }
      <ProjectView key={ project.slug } projectData={ project } />
    { /each }
    { #if filteredProjects.length === 0  }
      <p style={{ padding: '2rem 0', textAlign: 'center' }}>Sorry, i have no project with the specified filters!</p>
    {/if }
  </div>
</div>
